---
site_name: Template Repository
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Template Repository for sommerfeld.io projects.

repo_name: sommerfeld-io/template-repository
repo_url: https://github.com/sommerfeld-io/template-repository

copyright: >
  Copyright &copy; 2024 Sommerfeld.io |
  <a href="#__consent">Cookie settings</a>

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  font:
    text: Work Sans
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - content.code.copy
    - content.tabs.link
    # - navigation.tabs
    - navigation.footer
    # - navigation.sections
    - navigation.expand
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  consent:
    title: Cookie consent
    description: >-
      Our documentation website is hosted on GitHub Pages and uses services from GitHub,
      Google Fonts, and Kroki, each with their own terms and privacy policies. We do not
      control or influence the data these third parties may collect. The site itself does
      not set cookies, track users, or collect personal data. For detals, see our
      <a href="https://github.com/sommerfeld-io/.github/blob/main/docs/terms.md">Terms of Use</a>.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/template-repository
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/sommerfeldio

nav:
  - Home:
      - Startpage: index.md
      - license.md
      - Releases on GitHub ⧉: https://github.com/sommerfeld-io/template-repository/releases
      - Architecture Decision Records on GitHub ⧉: https://github.com/sommerfeld-io/template-repository/issues?q=is%3Aissue+label%3AADR
      - Security Policy ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/security.md
      - How to Contribute ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/contribute.md
      - Code of Conduct ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/code-of-conduct.md
      - Terms of Use ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/terms.md
  - How to Use:
      - usage/index.md
      - usage/markdown-components.md
