---
version: '3.42.1'

dotenv: ['.env']

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

tasks:

  internal:download:
    desc: 'Download file from central repo'
    internal: true
    silent: true
    cmds:
      - curl -fsSL -o "{{ .DEST }}" "{{ .URL }}"
      - chmod u+rw,g+rw,o+r "{{ .DEST }}"
    generates:
      - "{{ .DEST }}"

  internal:copy:
    desc: 'Do the actual work of copying files'
    internal: true
    silent: true
    cmds:
      - cp "{{ .SRC }}" "{{ .DEST }}"
      - chmod u+rw,g+rw,o+r "{{ .DEST }}"
    generates:
      - "{{ .DEST }}"

  # ===============================================================================================

  sync:assets-from-github:
    desc: 'Sync assets from the central sommerfeldio/.github repository'
    cmds:
      - echo "Syncing assets from the central sommerfeldio/.github repository..."
      - task: internal:download
        vars: { DEST: ".github/instructions/code-guideline-pipelines.md", URL: "{{ .REPO }}/refs/heads/main/docs/code-guideline-pipelines.md" }
      - task: internal:download
        vars: { DEST: ".github/instructions/pull-requests.yml", URL: "{{ .REPO }}/refs/heads/main/assets/github/instructions/pull-requests.yml" }
      - task: internal:download
        vars: { DEST: ".github/workflows/housekeeping-issues.yml", URL: "{{ .REPO }}/refs/heads/main/assets/github/workflows/housekeeping-issues.yml" }
      - task: internal:download
        vars: { DEST: ".github/workflows/housekeeping-labels.yml", URL: "{{ .REPO }}/refs/heads/main/assets/github/workflows/housekeeping-labels.yml" }

  # ===============================================================================================

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - find . -type f -exec chmod +r {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  docs:generate:
    desc: 'Generate Markdown files for documentation'
    cmds:
      - echo "Collecting documentation from other Markdown files ..."
      - task: internal:copy
        vars: { SRC: docs/index.md, DEST: README.md }
      - task: internal:copy
        vars: { SRC: docs/license.md, DEST: LICENSE.md }

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  # ===============================================================================================

  build:docker:
    desc: 'Lint and build container COMPOSE_SERVICE'
    vars:
      COMPOSE_SERVICE: 'app'
    cmds:
      - docker compose up {{ .COMPOSE_SERVICE }}-lint-dockerfile --exit-code-from {{ .COMPOSE_SERVICE }}-lint-dockerfile
      - docker compose build {{ .COMPOSE_SERVICE }}
