---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  update:
    desc: Update project dependencies and submodules
    cmds:
      - git submodule update --remote

  cleanup:filesystem:
    desc: Cleanup the filesystem for this project
    cmds:
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - task: update

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - task: cleanup:filesystem

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - task: cleanup:filesystem
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  copilot:lint-and-fix:
    desc: 'Use GitHub Copilot to lint and fix issues in the project'
    cmds:
      - task: cleanup
      - copilot --allow-all --prompt "/lint-and-fix"

  copilot:pull-request:
    desc: 'Use GitHub Copilot to create or update a pull request with a summary of all changes based on commit messages'
    cmds:
      - copilot --allow-all --prompt "/create-or-update-pull-request"

  # ===============================================================================================

  docs:generate:
    desc: 'Generate Markdown files for documentation'
    cmds:
      - echo "Collecting documentation from other Markdown files ..."
      - task: common:copy
        vars: { SRC: docs/index.md, DEST: README.md }
      - task: common:copy
        vars: { SRC: docs/license.md, DEST: LICENSE.md }

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - task: docs:generate
      - docker compose up docs-dev-server

  # ===============================================================================================

  build:docker:
    desc: 'Lint and build container COMPOSE_SERVICE'
    vars:
      COMPOSE_SERVICE: 'app'
    cmds:
      - docker compose up {{ .COMPOSE_SERVICE }}-lint-dockerfile --exit-code-from {{ .COMPOSE_SERVICE }}-lint-dockerfile
      - docker compose build {{ .COMPOSE_SERVICE }}
