---
version: '3.42.1'

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{.ITEM.LINTER}} --exit-code-from lint-{{.ITEM.LINTER}}

  # ===============================================================================================

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  # ===============================================================================================

  build:docker:
    desc: 'Lint and build container COMPOSE_SERVICE'
    vars:
      COMPOSE_SERVICE: 'app'
    cmds:
      - docker compose up {{.COMPOSE_SERVICE}}-lint-dockerfile --exit-code-from {{.COMPOSE_SERVICE}}-lint-dockerfile
      - docker compose build {{.COMPOSE_SERVICE}}
