---
# Copilot Agent Instructions: Auto-Request Reviewers

# This file provides guidance to automation tools and GitHub Copilot agent mode
# for automatically requesting code reviews on new pull requests.

pull_request:
  checklist:
    - Ensure the PR has a clear, descriptive title.
    - Confirm the PR description explains the purpose and scope of the change.
    - Verify that all CI checks have passed.
    - Ensure code passes all linter checks as configured in the repository.
    - Assign at least one reviewer.
  reviewers:
    always_request:
      - sebastian-sommerfeld-io
  merge_rules:
    # require_approval: false
    no_merge_conflicts: true
    title_and_commit_pattern: "^(fix|feat|build|chore|ci|docs|style|refactor|perf|test)/[a-z0-9._-]+$"

# Instructions for automation or Copilot agent:
# - Enforce the title_and_commit_pattern for both PR titles and all commit messages in the PR.
# - On PR creation: enforce the checklist, and assign reviewer(s).
# - On PR update: re-check the checklist, and notify user of missing items.
# - Only mark the PR as ready for review if all checklist items are satisfied.
# - Prevent merge if merge_rules are not satisfied.
